#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
source scripts/corra-release-env.sh

RELEASE_ROOT="release/corra-booth-${CORRA_APP_VERSION}-${CORRA_BUILD_ID}"
BUNDLE_DIR="$RELEASE_ROOT/bundle"
mkdir -p "$BUNDLE_DIR"

bash scripts/build-booth-ui-release.sh

mkdir -p "$BUNDLE_DIR/apps" "$BUNDLE_DIR/docs"
cp -R apps/booth-ui/dist "$BUNDLE_DIR/booth-ui-dist"
cp -R apps/desktop-electron "$BUNDLE_DIR/apps/desktop-electron"
cp docs/phase-9g-packaging-release-checklist.md "$BUNDLE_DIR/docs/" 2>/dev/null || true
cp docs/phase-9f-printer-kiosk-hardware-checklist.md "$BUNDLE_DIR/docs/" 2>/dev/null || true
cp docs/phase-9e-electron-disk-persistence-checklist.md "$BUNDLE_DIR/docs/" 2>/dev/null || true

cat > "$BUNDLE_DIR/release-manifest.json" <<JSON
{
  "appName": "$CORRA_APP_NAME",
  "version": "$CORRA_APP_VERSION",
  "channel": "$CORRA_RELEASE_CHANNEL",
  "buildId": "$CORRA_BUILD_ID",
  "commit": "$CORRA_COMMIT",
  "builtAt": "$CORRA_BUILT_AT",
  "notes": [
    "Release candidate bundle generated by scripts/make-corra-release-candidate.sh",
    "Test in Electron before distribution.",
    "Do not commit secrets or .env.local into public releases."
  ]
}
JSON

cat > "$BUNDLE_DIR/RUN-ELECTRON-WINDOWS.cmd" <<'CMD'
@echo off
setlocal
cd /d "%~dp0"
echo Corra Booth release bundle
echo.
echo Use the project Electron launcher / vendor Electron path for final Windows testing.
echo This bundle is a release candidate archive, not a signed installer yet.
echo.
pause
CMD

cat > "$RELEASE_ROOT/README.txt" <<TXT
Corra Booth Release Candidate

Version: $CORRA_APP_VERSION
Build ID: $CORRA_BUILD_ID
Commit: $CORRA_COMMIT
Built At: $CORRA_BUILT_AT

Contents:
- bundle/booth-ui-dist
- bundle/apps/desktop-electron
- bundle/release-manifest.json

Next:
1. Test in Electron on Windows.
2. Verify license activation.
3. Verify payment flow.
4. Verify camera/printer/kiosk.
5. Verify disk/cloud delivery.
TXT

echo "Release candidate generated: $RELEASE_ROOT"
