Write-Host "Corra Booth Windows Smoke Test Checklist"
Write-Host "========================================"
Write-Host "[ ] Installer launches"
Write-Host "[ ] App opens after install"
Write-Host "[ ] License activation screen works"
Write-Host "[ ] Booth mode opens"
Write-Host "[ ] Kiosk mode works"
Write-Host "[ ] Camera detected"
Write-Host "[ ] Photo capture works"
Write-Host "[ ] Printer detected"
Write-Host "[ ] Test print works"
Write-Host "[ ] Final output saved to disk"
Write-Host "[ ] Cloud upload works"
Write-Host "[ ] Payment flow works"
Write-Host "[ ] App restarts cleanly"
Write-Host "[ ] Uninstall works"
