import type { CorraThemeId, CorraThemePreset } from './types';

export const CORRA_THEME_PRESETS: Record<CorraThemeId, CorraThemePreset> = {
  y2k: {
    id: 'y2k',
    name: 'Y2K Pop',
    description: 'Pink, playful, retro digital booth look.',
    tokens: {
      primaryColor: '#EC4899',
      secondaryColor: '#F9A8D4',
      accentColor: '#FACC15',
      backgroundColor: '#FFF1F7',
      surfaceColor: '#FFFFFF',
      textColor: '#1C1917',
      mutedTextColor: '#78716C',
      borderColor: '#FBCFE8',
      radius: '2rem',
      fontHeading: 'Playfair Display, Georgia, serif',
      fontBody: 'Outfit, Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'gradient',
      value: 'radial-gradient(circle at top left, #FBCFE8, transparent 34%), radial-gradient(circle at bottom right, #FEF3C7, transparent 32%), #FFF1F7',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(255,255,255,0)',
    },
  },
  wedding: {
    id: 'wedding',
    name: 'Wedding',
    description: 'Soft cream, gold, romantic wedding booth.',
    tokens: {
      primaryColor: '#B88A44',
      secondaryColor: '#F5E6C8',
      accentColor: '#D6A95C',
      backgroundColor: '#FFF8EC',
      surfaceColor: '#FFFCF6',
      textColor: '#2C2117',
      mutedTextColor: '#8A7560',
      borderColor: '#EAD8B8',
      radius: '1.75rem',
      fontHeading: 'Playfair Display, Georgia, serif',
      fontBody: 'Outfit, Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #FFF8EC 0%, #F7E7C6 52%, #FFFDF8 100%)',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(255,255,255,0.1)',
    },
  },
  clean: {
    id: 'clean',
    name: 'Clean',
    description: 'Neutral, bright, simple modern interface.',
    tokens: {
      primaryColor: '#111827',
      secondaryColor: '#E5E7EB',
      accentColor: '#2563EB',
      backgroundColor: '#F8FAFC',
      surfaceColor: '#FFFFFF',
      textColor: '#111827',
      mutedTextColor: '#64748B',
      borderColor: '#E2E8F0',
      radius: '1.25rem',
      fontHeading: 'Inter, system-ui, sans-serif',
      fontBody: 'Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'solid',
      value: '#F8FAFC',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(255,255,255,0)',
    },
  },
  luxury: {
    id: 'luxury',
    name: 'Luxury',
    description: 'Black, champagne, premium self-photo studio.',
    tokens: {
      primaryColor: '#D4AF37',
      secondaryColor: '#2A2118',
      accentColor: '#F3D37A',
      backgroundColor: '#090909',
      surfaceColor: '#161616',
      textColor: '#FFF7E6',
      mutedTextColor: '#C7B99B',
      borderColor: '#3D3324',
      radius: '1.5rem',
      fontHeading: 'Playfair Display, Georgia, serif',
      fontBody: 'Outfit, Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'gradient',
      value: 'radial-gradient(circle at top, #2A2118, transparent 40%), #090909',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(0,0,0,0.2)',
    },
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate',
    description: 'Professional event booth for brands and offices.',
    tokens: {
      primaryColor: '#0F766E',
      secondaryColor: '#CCFBF1',
      accentColor: '#14B8A6',
      backgroundColor: '#F0FDFA',
      surfaceColor: '#FFFFFF',
      textColor: '#134E4A',
      mutedTextColor: '#5F7F7A',
      borderColor: '#99F6E4',
      radius: '1.25rem',
      fontHeading: 'Inter, system-ui, sans-serif',
      fontBody: 'Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'solid',
      value: '#F0FDFA',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(255,255,255,0)',
    },
  },
  kids: {
    id: 'kids',
    name: 'Kids Party',
    description: 'Bright colorful booth for birthday and family events.',
    tokens: {
      primaryColor: '#8B5CF6',
      secondaryColor: '#FDE68A',
      accentColor: '#FB7185',
      backgroundColor: '#FEF3C7',
      surfaceColor: '#FFFFFF',
      textColor: '#312E81',
      mutedTextColor: '#7C3AED',
      borderColor: '#DDD6FE',
      radius: '2rem',
      fontHeading: 'Outfit, Inter, system-ui, sans-serif',
      fontBody: 'Outfit, Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'gradient',
      value: 'radial-gradient(circle at 20% 20%, #FDE68A, transparent 28%), radial-gradient(circle at 80% 30%, #FBCFE8, transparent 28%), radial-gradient(circle at 50% 90%, #C4B5FD, transparent 30%), #FFF7ED',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(255,255,255,0)',
    },
  },
  retro: {
    id: 'retro',
    name: 'Retro',
    description: 'Warm vintage booth look.',
    tokens: {
      primaryColor: '#B45309',
      secondaryColor: '#FED7AA',
      accentColor: '#EA580C',
      backgroundColor: '#FFF7ED',
      surfaceColor: '#FFFBEB',
      textColor: '#431407',
      mutedTextColor: '#9A3412',
      borderColor: '#FDBA74',
      radius: '1.4rem',
      fontHeading: 'Playfair Display, Georgia, serif',
      fontBody: 'Outfit, Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #FFF7ED 0%, #FED7AA 100%)',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(120,53,15,0.08)',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Plain monochrome interface.',
    tokens: {
      primaryColor: '#18181B',
      secondaryColor: '#F4F4F5',
      accentColor: '#71717A',
      backgroundColor: '#FAFAFA',
      surfaceColor: '#FFFFFF',
      textColor: '#18181B',
      mutedTextColor: '#71717A',
      borderColor: '#E4E4E7',
      radius: '1rem',
      fontHeading: 'Inter, system-ui, sans-serif',
      fontBody: 'Inter, system-ui, sans-serif',
    },
    defaultBackground: {
      type: 'solid',
      value: '#FAFAFA',
      fit: 'cover',
      opacity: 1,
      overlayColor: 'rgba(255,255,255,0)',
    },
  },
};

export function getThemePreset(themeId: CorraThemeId): CorraThemePreset {
  return CORRA_THEME_PRESETS[themeId] || CORRA_THEME_PRESETS.y2k;
}
